/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-06-13 10:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminAfterLogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.DoctorDao;
import com.entity.Doctors;
import com.dao.SpecialistDao;
import com.entity.Specialities;
import java.util.List;
import com.entity.Users;

public final class doctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/adminAfterLogin/adminNavbar.jsp", Long.valueOf(1712663459884L));
    _jspx_dependants.put("/adminAfterLogin/../component/footer.jsp", Long.valueOf(1711738444584L));
    _jspx_dependants.put("/adminAfterLogin/../component/JsScripts.jsp", Long.valueOf(1711534809650L));
    _jspx_dependants.put("/adminAfterLogin/../component/message.jsp", Long.valueOf(1711532449754L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.entity.Doctors");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dao.DoctorDao");
    _jspx_imports_classes.add("com.entity.Specialities");
    _jspx_imports_classes.add("com.dao.SpecialistDao");
    _jspx_imports_classes.add("com.entity.Users");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/44e8cd70ef.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Bootstrap Icon -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"component/styles.css\">\r\n");
      out.write("<title>AdminPage</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	padding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".anchor:hover {\r\n");
      out.write("	color: rgb(209, 210, 223) !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"d-flex flex-column min-vh-100\">\r\n");
      out.write("\r\n");
      out.write("	<!-- navbar Starts -->\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand fs-3\" href=\"../index.jsp\"> <i\r\n");
      out.write("			class=\"fa-regular fa-hospital\"></i> HEALTHIFY\r\n");
      out.write("		</a>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"text-white  m-4 anchor\" href=\"adminIndex.jsp\"> HOME</a> <a\r\n");
      out.write("				class=\"text-white m-4 anchor\" href=\"doctor.jsp\"> VIEW DOCTORS</a> <a\r\n");
      out.write("				type=\"button\" class=\"text-white m-4 anchor\"\r\n");
      out.write("				href=\"viewAllAppointment.jsp\"> VIEW PATIENTS</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"dropdown mx-5 \">\r\n");
      out.write("			<a class=\"btn btn-dark text-capitalize dropdown-toggle\" href=\"#\"\r\n");
      out.write("				role=\"button\" id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("				aria-expanded=\"false\"> ADMIN <i\r\n");
      out.write("				class=\"fa-solid fa-user-tie mx-1\"></i>\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"../adminLogoutServlet\">Logout</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("	<!-- navbar Ends -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Message Component Starts -->\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

String messageString = (String) session.getAttribute("messageFromServer");
if (messageString != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show mb-0 text-center\"\r\n");
      out.write("	role=\"alert\">\r\n");
      out.write("	<strong>");
      out.print(messageString);
      out.write("</strong>\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("messageFromServer");
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("	<!-- Message Component End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Starts -->\r\n");
      out.write("	");

	response.setHeader("Cache-Control", "no-cache");

	//Forces caches to obtain a new copy of the page from the origin server
	response.setHeader("Cache-Control", "no-store");

	//Directs caches not to store the page under any circumstance
	response.setDateHeader("Expires", 0);

	//Causes the proxy cache to see the page as "stale"
	response.setHeader("Pragma", "no-cache");
	//HTTP 1.0 backward enter code here
	
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Ends -->\r\n");
      out.write("	");

	if (session.getAttribute("adminObject") == null) {
		response.sendRedirect("../adminLogin.jsp");
		session.invalidate();
	}
	
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"text-center m-3\">\r\n");
      out.write("		<a href=\"adminIndex.jsp\"><button\r\n");
      out.write("				class=\"btn btn-primary rounded-pill\">Go To Home</button></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Doctor page Content Starts -->\r\n");
      out.write("	<section class=\" p-3 sm:p-5 h-screen\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"relative overflow-hidden  shadow-md bg-gray-800 sm:rounded-lg\">\r\n");
      out.write("				<div class=\"overflow-x-auto\">\r\n");
      out.write("					<table class=\"w-full text-sm text-left table table-striped \">\r\n");
      out.write("						<!-- w-full text-sm text-left text-gray-500 dark:text-gray-400 -->\r\n");
      out.write("						<thead\r\n");
      out.write("							class=\"text-base uppercase text-white dark:border-gray-700 dark:text-gray-400\">\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">FullName</th>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">Qualification</th>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">Specialization</th>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">Email</th>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">Mobile</th>\r\n");
      out.write("								<th scope=\"col\" class=\"px-4 py-3\">Actions</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

							List<Doctors> docList = DoctorDao.getAllDoctors();
							for (Doctors d : docList) {
							
      out.write("\r\n");
      out.write("							<tr class=\"border-b bg-gray-50 dark:border-gray-40\">\r\n");
      out.write("								<th scope=\"row\"\r\n");
      out.write("									class=\"px-4 py-3 font-medium whitespace-nowrap dark:text-white\">\r\n");
      out.write("									");
      out.print(d.getFullNameString());
      out.write("</th>\r\n");
      out.write("								<td class=\"px-4 font-semibold py-3\">");
      out.print(d.getQualificationString());
      out.write("</td>\r\n");
      out.write("								<td class=\"px-4 font-semibold py-3\">");
      out.print(d.getSpecializationString());
      out.write("</td>\r\n");
      out.write("								<td class=\"px-4 font-semibold py-3\">");
      out.print(d.getEmailString());
      out.write("</td>\r\n");
      out.write("								<td class=\"px-4 font-semibold py-3\">");
      out.print(d.getMobileNumberString());
      out.write("</td>\r\n");
      out.write("								<td class=\"px-4 font-semibold py-3 flex items-center gap-2\">\r\n");
      out.write("									<a href=\"editDoctorDetails.jsp?doctorId=");
      out.print(d.getId());
      out.write("\"><button\r\n");
      out.write("											class=\"bg-blue-700 p-1 font-semibold rounded-md hover:bg-blue-500\">Edit</button></a>\r\n");
      out.write("									<input type=\"hidden\" name=\"id\" value=\"\"> <a\r\n");
      out.write("									href=\"../DeletDoctorServet?doctorId=");
      out.print(d.getId());
      out.write("\">\r\n");
      out.write("										<button type=\"submit\"\r\n");
      out.write("											class=\"bg-red-700 p-1 font-semibold rounded-md hover:bg-red-500 overflow-hidden\">Delete</button>\r\n");
      out.write("								</a>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Doctor page Content Ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Starts  -->\r\n");
      out.write("	");
      out.write("<footer class=\"site-footer bg-dark mt-auto\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<a class=\"nav-link active text-white\" aria-current=\"page\"\r\n");
      out.write("					href=\"https://www.facebook.com/\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("				<a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://twitter.com/i/flow/login\"><i\r\n");
      out.write("					class=\"bi bi-twitter-x\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww.linkedin.com%2Ffeed%2F\"><i\r\n");
      out.write("					class=\"bi bi-linkedin\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.instagram.com/accounts/login/\"><i\r\n");
      out.write("					class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<p class=\"copyright-text text-secondary\">Copyright@2024 All\r\n");
      out.write("					Rights Reserved By Healthii</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<!-- Footer Ends  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Starts  -->\r\n");
      out.write("	");
      out.write("<!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("	<!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\" integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Ends  -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
