/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-06-10 13:12:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.http.HttpResponse;
import com.entity.Users;
import com.entity.Users;

public final class adminLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/component/footer.jsp", Long.valueOf(1711738444584L));
    _jspx_dependants.put("/component/JsScripts.jsp", Long.valueOf(1711534809650L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1712663426304L));
    _jspx_dependants.put("/component/message.jsp", Long.valueOf(1711532449754L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.entity.Users");
    _jspx_imports_classes.add("java.net.http.HttpResponse");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/44e8cd70ef.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Bootstrap Icon -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("<title>AdminLogin</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	padding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".anchor:hover {\r\n");
      out.write("	color: rgb(2, 17, 227) !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- navbar Starts -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand fs-3\" href=\"index.jsp\"> <i\r\n");
      out.write("			class=\"fa-regular fa-hospital\"></i> HEALTHIFY\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarNavAltMarkup\"\r\n");
      out.write("			aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("			<div class=\"navbar-nav ms-auto px-5\">\r\n");
      out.write("				<a class=\"nav-link\" aria-current=\"page\" href=\"index.jsp\">HOME</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"adminLogin.jsp\">ADMIN</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"doctorLogin.jsp\">DOCTOR</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"userAfterLogin/userIndex.jsp\">BOOK APPOINTMENT</a><a\r\n");
      out.write("					class=\"nav-link\" href=\"userLogin.jsp\">USER</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<!-- navbar Ends -->\r\n");
      out.write("	<!-- Message Component Starts -->\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

String messageString = (String) session.getAttribute("messageFromServer");
if (messageString != null) {

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show mb-0 text-center\"\r\n");
      out.write("	role=\"alert\">\r\n");
      out.write("	<strong>");
      out.print(messageString);
      out.write("</strong>\r\n");
      out.write("	<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("		aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");

session.removeAttribute("messageFromServer");
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("	<!-- Message Component Starts -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Starts -->\r\n");
      out.write("	");

	response.setHeader("Cache-Control", "no-cache");

	//Forces caches to obtain a new copy of the page from the origin server
	response.setHeader("Cache-Control", "no-store");

	//Directs caches not to store the page under any circumstance
	response.setDateHeader("Expires", 0);

	//Causes the proxy cache to see the page as "stale"
	response.setHeader("Pragma", "no-cache");
	//HTTP 1.0 backward enter code here
	
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Ends -->\r\n");
      out.write("	<div class=\"container text-center\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"col-12 col-lg-6 p-3 border bg-dark d-flex justify-content-center align-items-center\">\r\n");
      out.write("				<div class=\"modal-body bg-white\">\r\n");
      out.write("					<form action=\"AdminLogin\" method=\"post\">\r\n");
      out.write("						<div class=\"card-body text-dark\">\r\n");
      out.write("							<i class=\"fa-solid fa-key fa-3x\"></i>\r\n");
      out.write("							<p class=\"card-text text-info h3\">ADMIN LOGIN</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					<!--	<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"email\" required class=\"form-control\" id=\"femail\"\r\n");
      out.write("								placeholder=\"Email\" name=\"adminEmail\"> <label\r\n");
      out.write("								for=\"femail\">Email</label>\r\n");
      out.write("						</div> -->\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"text\" required class=\"form-control\" id=\"femail\"\r\n");
      out.write("								placeholder=\"Email\" name=\"adminEmail\"> <label\r\n");
      out.write("								for=\"femail\">Username</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"password\" required class=\"form-control\" id=\"fpass\"\r\n");
      out.write("								placeholder=\"Password\" name=\"adminPassword\"> <label\r\n");
      out.write("								for=\"fpass\">Password</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\"\r\n");
      out.write("							class=\"btn w-100 btn-primary text-light btn-lg btn-block\">LOGIN</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-lg-6\">\r\n");
      out.write("				<img src=\"images/adminlogin.jpg\"\r\n");
      out.write("					class=\"rounded img-fluid h-100 cover\" style=\"object: fit-cover;\"\r\n");
      out.write("					alt=\"admin picture\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Starts  -->\r\n");
      out.write("	");
      out.write("<footer class=\"site-footer bg-dark mt-auto\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<a class=\"nav-link active text-white\" aria-current=\"page\"\r\n");
      out.write("					href=\"https://www.facebook.com/\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("				<a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://twitter.com/i/flow/login\"><i\r\n");
      out.write("					class=\"bi bi-twitter-x\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww.linkedin.com%2Ffeed%2F\"><i\r\n");
      out.write("					class=\"bi bi-linkedin\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.instagram.com/accounts/login/\"><i\r\n");
      out.write("					class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<p class=\"copyright-text text-secondary\">Copyright@2024 All\r\n");
      out.write("					Rights Reserved By Healthii</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<!-- Footer Ends  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Starts  -->\r\n");
      out.write("	");
      out.write("<!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("	<!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\" integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Ends  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
