/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-06-10 13:11:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entity.Users;
import com.entity.Users;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/component/JsScripts.jsp", Long.valueOf(1711534809650L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1712663426304L));
    _jspx_dependants.put("/component/IndexPageFooter.jsp", Long.valueOf(1711460214662L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.entity.Users");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/44e8cd70ef.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Bootstrap Icon -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"component/styles.css\">\r\n");
      out.write("<title>WelcomePageHealthii</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	padding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".anchor:hover {\r\n");
      out.write("	color: rgb(2, 17, 227) !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- navbar Starts -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand fs-3\" href=\"index.jsp\"> <i\r\n");
      out.write("			class=\"fa-regular fa-hospital\"></i> HEALTHIFY\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarNavAltMarkup\"\r\n");
      out.write("			aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("			<div class=\"navbar-nav ms-auto px-5\">\r\n");
      out.write("				<a class=\"nav-link\" aria-current=\"page\" href=\"index.jsp\">HOME</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"adminLogin.jsp\">ADMIN</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"doctorLogin.jsp\">DOCTOR</a> <a\r\n");
      out.write("					class=\"nav-link\" href=\"userAfterLogin/userIndex.jsp\">BOOK APPOINTMENT</a><a\r\n");
      out.write("					class=\"nav-link\" href=\"userLogin.jsp\">USER</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<!-- navbar Ends -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Message Component Starts -->\r\n");
      out.write("	<!-- Message Component End -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Clearing Cache Starts -->\r\n");
      out.write("	");

	response.setHeader("Cache-Control", "no-cache");

	//Forces caches to obtain a new copy of the page from the origin server
	response.setHeader("Cache-Control", "no-store");

	//Directs caches not to store the page under any circumstance
	response.setDateHeader("Expires", 0);

	//Causes the proxy cache to see the page as "stale"
	response.setHeader("Pragma", "no-cache");
	//HTTP 1.0 backward enter code here
	
      out.write("\r\n");
      out.write("	<!-- Clearing Cache Ends -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Sliding images Starts -->\r\n");
      out.write("	<div class=\"container-fluid mb-5\">\r\n");
      out.write("		<div id=\"carouselExampleIndicators\"\r\n");
      out.write("			class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n");
      out.write("			<div class=\"carousel-indicators\">\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("					data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("					aria-label=\"Slide 1\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("					data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("					data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"images/doc2.jpg\" class=\"d-block w-100 img-fluid\"\r\n");
      out.write("						alt=\"...\" height=\"530px\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item active\">\r\n");
      out.write("					<img src=\"images/doc3.jpg\" class=\"d-block w-100 img-fluid\"\r\n");
      out.write("						alt=\"...\" height=\"530px\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"images/doctor1.jpg\" class=\"d-block w-100 img-fluid\"\r\n");
      out.write("						alt=\"...\" height=\"530px\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Sliding images End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- key features using grid box Starts -->\r\n");
      out.write("	<div class=\"container mb-5 \" id=\"keyFeatures\">\r\n");
      out.write("		<p class=\"text-center fs-2 mb-5 text-info h1\">Taking care of your\r\n");
      out.write("			health</p>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-4\">\r\n");
      out.write("				<div class=\"card shadow-lg border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col text-center\">\r\n");
      out.write("									<img src=\"images/doctor.png\" alt=\"\" height=\"60px\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<h5 class=\"card-title text-center text-success\">Qualified\r\n");
      out.write("										Doctors</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"card-text text-secondary\" style=\"text-align: justify;\">Lorem\r\n");
      out.write("							ipsum dolor sit amet consectetur adipisicing elit. Beatae enim\r\n");
      out.write("							aliquam tenetur odio inventore velit, sequi quis eius vel\r\n");
      out.write("							voluptas quae expedita quaerat cupiditate blanditiis ducimus\r\n");
      out.write("							soluta itaque aspernatur, illum consequuntur rem deserunt\r\n");
      out.write("							voluptates? Inventore ducimus officiis tempora numquam\r\n");
      out.write("							consequatur velit ad assumenda molestias veniam.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-4\">\r\n");
      out.write("				<div class=\"card shadow-lg border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col text-center\">\r\n");
      out.write("									<img src=\"images/24-7.png\" alt=\"\" height=\" 60px\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<h5 class=\"card-title text-center text-success\">24/7\r\n");
      out.write("										Service Availabe</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"card-text text-secondary\" style=\"text-align: justify;\">Lorem\r\n");
      out.write("							ipsum dolor sit amet consectetur adipisicing elit. Beatae enim\r\n");
      out.write("							aliquam tenetur odio inventore velit, sequi quis eius vel\r\n");
      out.write("							voluptas quae expedita quaerat cupiditate blanditiis ducimus\r\n");
      out.write("							soluta itaque aspernatur, illum consequuntur rem deserunt\r\n");
      out.write("							voluptates? Inventore ducimus officiis tempora numquam\r\n");
      out.write("							consequatur velit ad assumenda molestias Lorem, ipsum dolor.\r\n");
      out.write("							Lorem ipsum dolor sit.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-4\">\r\n");
      out.write("				<div class=\"card shadow-lg border-0\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col text-center\">\r\n");
      out.write("									<img src=\"images/emergency-services.png\" alt=\"\" height=\"60px\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<h5 class=\"card-title text-center text-success\">Emergency\r\n");
      out.write("										Care</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"card-text text-secondary\" style=\"text-align: justify;\">Lorem\r\n");
      out.write("							ipsum dolor sit amet consectetur adipisicing elit. Beatae enim\r\n");
      out.write("							aliquam tenetur odio inventore velit, sequi quis eius vel\r\n");
      out.write("							voluptas quae expedita quaerat cupiditate blanditiis ducimus\r\n");
      out.write("							soluta itaque aspernatur, illum consequuntur rem deserunt\r\n");
      out.write("							voluptates? Inventore ducimus officiis tempora numquam\r\n");
      out.write("							consequatur velit ad assumenda molestias sum dolor sit amet\r\n");
      out.write("							consectetur.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- key features using grid box Ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- About Section Starts -->\r\n");
      out.write("	<div class=\"container\" style=\"margin-bottom: 3rem;\" id=\"aboutUs\">\r\n");
      out.write("		<p class=\"text-center fs-2 mb-5 text-info h1\">About us</p>\r\n");
      out.write("		<!-- row-1 -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12 col-lg-6\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col text-center\">\r\n");
      out.write("							<img src=\"images/midical.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-lg-6\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col\">\r\n");
      out.write("							<h5 class=\"card-title text-center h3 text-success\">About\r\n");
      out.write("								Healthii</h5>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col text-center\">\r\n");
      out.write("							<p class=\"card-text text-secondary\" style=\"text-align: justify;\">\r\n");
      out.write("								Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae\r\n");
      out.write("								enim aliquam tenetur odio inventore velit, sequi quis eius vel\r\n");
      out.write("								voluptas quae expedita quaerat cupiditate blanditiis ducimus\r\n");
      out.write("								soluta itaque aspernatur, illum consequuntur rem deserunt\r\n");
      out.write("								voluptates? Inventore ducimus officiis tempora numquam\r\n");
      out.write("								consequatur velit ad assumenda molestias veniam. <br> <br>\r\n");
      out.write("								Lorem ipsum dolor sit Lorem ipsum dolor sit amet consectetur,\r\n");
      out.write("								adipisicing elit. Necessitatibus, omnis Lorem ipsum dolor sit\r\n");
      out.write("								amet consectetur adipisicing elit. Ullam, aliquid. consectetur\r\n");
      out.write("								adipisicing elit. Officiis suscipit quisquam quidem odio fuga\r\n");
      out.write("								possimus quis, praesentium dolores. Lorem ipsum dolor sit amet\r\n");
      out.write("								consectetur.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- row-2 -->\r\n");
      out.write("		<div class=\"row mt-5\">\r\n");
      out.write("			<div class=\"col-12 col-lg-6\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col text-center\">\r\n");
      out.write("							<img src=\"images/bed.jpg\" alt=\"\" class=\"img-fluid mt-1\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-lg-6\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12 col-lg-6\">\r\n");
      out.write("							<div class=\"card shadow border-0\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col text-center\">\r\n");
      out.write("												<img src=\"images/first-aid-kit.png\" alt=\"\" height=\"35px\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col\">\r\n");
      out.write("												<h6 class=\"card-title text-center text-success\">PRIMARY\r\n");
      out.write("													CARE</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"card-text text-secondary\"\r\n");
      out.write("										style=\"text-align: justify;\">Lorem ipsum dolor sit amet\r\n");
      out.write("										consectetur adipisicing elit. Beatae Lorem, ipsum dolor.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-lg-6\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card shadow border-0\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col text-center\">\r\n");
      out.write("												<img src=\"images/lab.png\" alt=\"\" height=\"35px\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col\">\r\n");
      out.write("												<h6 class=\"card-title text-center text-success\">LAB\r\n");
      out.write("													TEST</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"card-text text-secondary\"\r\n");
      out.write("										style=\"text-align: justify;\">Lorem ipsum dolor sit amet\r\n");
      out.write("										consectetur adipisicing elit. Beatae Lorem, ipsum dolor.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row mt-1\">\r\n");
      out.write("						<div class=\"col-12 col-lg-6\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card shadow border-0\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col text-center\">\r\n");
      out.write("												<img src=\"images/medical-checkup.png\" alt=\"\" height=\"35px\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col\">\r\n");
      out.write("												<h6 class=\"card-title text-center text-success\">SYMPTOM\r\n");
      out.write("													CHECK</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"card-text text-secondary\"\r\n");
      out.write("										style=\"text-align: justify;\">Lorem ipsum dolor sit amet\r\n");
      out.write("										consectetur adipisicing elit. Beatae Lorem, ipsum dolor.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-lg-6\">\r\n");
      out.write("							<div class=\"card shadow border-0\">\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<div class=\"container\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col text-center\">\r\n");
      out.write("												<img src=\"images/heart-rate.png\" alt=\"\" height=\"35px\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col\">\r\n");
      out.write("												<h6 class=\"card-title text-center text-success\">HEART\r\n");
      out.write("													RATE</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"card-text text-secondary\"\r\n");
      out.write("										style=\"text-align: justify;\">Lorem ipsum dolor sit amet\r\n");
      out.write("										consectetur adipisicing elit. Beatae Lorem, ipsum dolor.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- About Section Ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ContactUs Starts -->\r\n");
      out.write("	<div class=\"container mb-5\" id=\"contactUs\">\r\n");
      out.write("		<p class=\"text-center fs-2 mb-5 text-info h1\">Contact us</p>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-7\">\r\n");
      out.write("				<h4 class=\"text-success\">Get in touch</h4>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"ContactName\" class=\"form-label\">Name</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control\" name=\"\" id=\"ContactName\"\r\n");
      out.write("						placeholder=\"Enter your name\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"ContactEmail\" class=\"form-label\">Email</label> <input\r\n");
      out.write("						type=\"email\" class=\"form-control\" name=\"\" id=\"ContactEmail\"\r\n");
      out.write("						placeholder=\"Enter your email\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"ContactNumber\" class=\"form-label\">Contact\r\n");
      out.write("						Number</label> <input type=\"tel\" class=\"form-control\" name=\"\"\r\n");
      out.write("						id=\"ContactNumber\" placeholder=\"contact number\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<label for=\"ContactMessage\" class=\"form-label\">Message</label>\r\n");
      out.write("					<textarea class=\"form-control\" name=\"\" id=\"ContactMessage\" rows=\"4\"\r\n");
      out.write("						placeholder=\"Message\"></textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("					<button type=\"submit\" data-bs-toggle=\"modal\"\r\n");
      out.write("						class=\"btn w-100 btn-primary btn-lg btn-block close\">SEND\r\n");
      out.write("						US</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-5\">\r\n");
      out.write("				<h4 class=\"text-success\">Contact Details</h4>\r\n");
      out.write("				<div class=\"mt-5 \">\r\n");
      out.write("					<div class=\"d-flex gap-2 mt-4\">\r\n");
      out.write("						<i class=\"h6 bi bi-geo-alt-fill\"></i>\r\n");
      out.write("						<p class=\"h6 text-secondary\">Address : 198 west 21th street,\r\n");
      out.write("							opposite to k-mart, Raipur</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex gap-2 mt-4\">\r\n");
      out.write("						<i class=\"h6 bi bi-telephone-fill\"></i>\r\n");
      out.write("						<p class=\"h6 text-secondary\">Contact : 8745678934</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex gap-2 mt-4\">\r\n");
      out.write("						<i class=\"h6 bi bi-envelope-fill\"></i>\r\n");
      out.write("						<p class=\"h6 text-secondary\">Email : testing@gamil.com</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex gap-2 mt-4\">\r\n");
      out.write("						<i class=\"h6 bi bi-browser-chrome\"></i>\r\n");
      out.write("						<p class=\"h6 text-secondary\">Website : www.testing.com</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ContactUs Ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--User Register Modal Starts-->\r\n");
      out.write("	<div class=\"modal fade\" id=\"register\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h3 class=\"modal-title text-primary\" id=\"exampleModalLongTitle\">Register</h3>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"UserRegister\" method=\"post\">\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"text\" required class=\"form-control\" id=\"fname\"\r\n");
      out.write("								placeholder=\"Username\" name=\"username\"> <label\r\n");
      out.write("								for=\"fname\">Username</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"email\" required class=\"form-control\" id=\"femail\"\r\n");
      out.write("								placeholder=\"Email\" name=\"email\"> <label for=\"femail\">Email</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"password\" required class=\"form-control\" id=\"fpass\"\r\n");
      out.write("								placeholder=\"Password\" name=\"password\"> <label\r\n");
      out.write("								for=\"fpass\">Password</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\"\r\n");
      out.write("							class=\"btn w-100 btn-primary btn-lg btn-block\">Register</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text-center mb-4 hover-overlay\">\r\n");
      out.write("					<button type=\"button\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#login\" class=\"close border-0 bg-white anchor\"\r\n");
      out.write("						data-bs-dismiss=\"modal\" aria-label=\"Close\">I already have\r\n");
      out.write("						an account</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--User Register Modal Ends-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--User Login Modal Starts-->\r\n");
      out.write("	<div class=\"modal fade\" id=\"login\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h3 class=\"modal-title text-primary\" id=\"exampleModalLongTitle\">Login</h3>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"\">\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"email\" required class=\"form-control\" id=\"femail\"\r\n");
      out.write("								placeholder=\"Email\"> <label for=\"femail\">Email</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"password\" required class=\"form-control\" id=\"fpass\"\r\n");
      out.write("								placeholder=\"Password\"> <label for=\"fpass\">Password</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\"\r\n");
      out.write("							class=\"btn w-100 btn-primary btn-lg btn-block\">Login</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text-center mb-4 hover-overlay\">\r\n");
      out.write("					<button type=\"button\" data-bs-toggle=\"modal\"\r\n");
      out.write("						data-bs-target=\"#register\" class=\"close border-0 bg-white anchor\"\r\n");
      out.write("						data-bs-dismiss=\"modal\" aria-label=\"Close\">Don't have an\r\n");
      out.write("						account</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--User Login Modal Ends-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--Admin Login Modal Starts-->\r\n");
      out.write("	<div class=\"modal fade\" id=\"adminLoginModal\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\"\r\n");
      out.write("		aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h3 class=\"modal-title text-primary\" id=\"exampleModalLongTitle\">Admin\r\n");
      out.write("						Login</h3>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"AdminLogin\" method=\"post\">\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"email\" required class=\"form-control\" id=\"femail\"\r\n");
      out.write("								placeholder=\"Email\" name=\"adminEmail\"> <label\r\n");
      out.write("								for=\"femail\">Email</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-floating mb-2\">\r\n");
      out.write("							<input type=\"password\" required class=\"form-control\" id=\"fpass\"\r\n");
      out.write("								placeholder=\"Password\" name=\"adminPassword\"> <label\r\n");
      out.write("								for=\"fpass\">Password</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\" data-bs-toggle=\"modal\"\r\n");
      out.write("							class=\"btn w-100 btn-primary btn-lg btn-block close\">Login</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--Admin Login Modal Ends-->\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Starts  -->\r\n");
      out.write("	");
      out.write("<footer class=\"site-footer bg-dark\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<a class=\"nav-link active text-white\" aria-current=\"page\"\r\n");
      out.write("					href=\"https://www.facebook.com/\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("				<a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://twitter.com/i/flow/login\"><i\r\n");
      out.write("					class=\"bi bi-twitter-x\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww.linkedin.com%2Ffeed%2F\"><i\r\n");
      out.write("					class=\"bi bi-linkedin\"></i></a> <a class=\"nav-link text-white\"\r\n");
      out.write("					href=\"https://www.instagram.com/accounts/login/\"><i\r\n");
      out.write("					class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<a class=\"nav-link active text-white\" aria-current=\"page\" href=\"#\">HOME</a>\r\n");
      out.write("				<a class=\"nav-link text-white\" href=\"#aboutUs\">ABOUT</a> <a\r\n");
      out.write("					class=\"nav-link text-white\" href=\"#keyFeatures\">SERVICES</a> <a\r\n");
      out.write("					class=\"nav-link text-white\" href=\"#contactUs\">CONTACT</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"d-flex flex-row justify-content-center\">\r\n");
      out.write("				<p class=\"copyright-text text-secondary\">Copyright@2024 All\r\n");
      out.write("					Rights Reserved By Healthii</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<!-- Footer Ends  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Starts  -->\r\n");
      out.write("	");
      out.write("<!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("	<!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\" integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->");
      out.write("\r\n");
      out.write("	<!-- JavaScripts Ends  -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
